packages:
  - 'packages/*'
  - 'apps/ddaas'

shared-workspace-lockfile: true
prefer-workspace-packages: true
save-workspace-protocol: true

# 统一版本管理 - Catalogs
catalog:
  # React 生态
  "react": "19.1.0"
  "react-dom": "19.1.0"
  "next": "15.3.2"
  "next-intl": "^3.26.5"
  "next-themes": "^0.4.6"
  
  # UI 组件库
  "@radix-ui/react-accordion": "^1.2.10"
  "@radix-ui/react-alert-dialog": "^1.1.13"
  "@radix-ui/react-aspect-ratio": "^1.1.6"
  "@radix-ui/react-avatar": "^1.1.9"
  "@radix-ui/react-checkbox": "^1.3.1"
  "@radix-ui/react-collapsible": "^1.1.10"
  "@radix-ui/react-context-menu": "^2.2.14"
  "@radix-ui/react-dialog": "^1.1.13"
  "@radix-ui/react-dropdown-menu": "^2.1.14"
  "@radix-ui/react-hover-card": "^1.1.13"
  "@radix-ui/react-label": "^2.1.6"
  "@radix-ui/react-menubar": "^1.1.14"
  "@radix-ui/react-navigation-menu": "^1.2.12"
  "@radix-ui/react-popover": "^1.1.13"
  "@radix-ui/react-progress": "^1.1.6"
  "@radix-ui/react-radio-group": "^1.3.6"
  "@radix-ui/react-scroll-area": "^1.2.8"
  "@radix-ui/react-select": "^2.2.4"
  "@radix-ui/react-separator": "^1.1.6"
  "@radix-ui/react-slider": "^1.3.4"
  "@radix-ui/react-slot": "^1.2.2"
  "@radix-ui/react-switch": "^1.2.4"
  "@radix-ui/react-tabs": "^1.1.11"
  "@radix-ui/react-toast": "^1.2.13"
  "@radix-ui/react-toggle": "^1.1.8"
  "@radix-ui/react-toggle-group": "^1.1.9"
  "@radix-ui/react-tooltip": "^1.2.6"
  
  # 用户认证
  "@clerk/localizations": "^3.16.0"
  "@clerk/nextjs": "^6.19.4"
  "@clerk/themes": "^2.2.45"
  "@clerk/types": "^4.59.0"
  
  # 样式相关
  "tailwindcss": "^4.1.7"
  "@tailwindcss/typography": "latest"
  "@tailwindcss/postcss": "^4.1.7"
  "tailwind-merge": "^3.3.0"
  "tailwindcss-animate": "^1.0.7"
  "autoprefixer": "^10.4.21"
  "postcss": "^8.5.3"
  
  # 表单处理
  "react-hook-form": "^7.56.3"
  "@hookform/resolvers": "^3.10.0"
  "zod": "^3.24.4"
  
  # 文档系统
  "fumadocs-core": "15.3.3"
  "fumadocs-docgen": "2.0.0"
  "fumadocs-mdx": "11.6.3"
  "fumadocs-typescript": "4.0.4"
  "fumadocs-ui": "15.3.3"
  
  # 工具库
  "clsx": "^2.1.1"
  "class-variance-authority": "^0.7.1"
  "lucide-react": "^0.511.0"
  "date-fns": "2.30.0"
  "katex": "^0.16.22"
  "mermaid": "^11.6.0"
  "shiki": "^3.4.2"
  "sonner": "^1.7.4"
  "cmdk": "1.0.4"
  "input-otp": "1.4.2"
  "vaul": "^0.9.9"
  "embla-carousel-react": "8.5.1"
  "react-day-picker": "8.10.1"
  "react-medium-image-zoom": "^5.2.14"
  "react-resizable-panels": "^2.1.9"
  "recharts": "2.15.3"
  "ts-morph": "25.0.1"
  
  # Markdown 处理
  "remark": "^15.0.1"
  "remark-gfm": "^4.0.1"
  "remark-math": "^6.0.0"
  "remark-mdx": "^3.1.0"
  "remark-frontmatter": "^5.0.0"
  "rehype-katex": "^7.0.1"
  "@types/mdx": "^2.0.13"
  
  # 开发工具
  "typescript": "^5.8.3"
  "eslint": "^9.27.0"
  "eslint-config-next": "15.3.2"
  "eslint-plugin-unused-imports": "^4.1.4"
  "@typescript-eslint/parser": "^8.32.1"
  "ts-node": "^10.9.2"
  
  # 类型定义
  "@types/node": "^22.15.18"
  "@types/react": "19.1.2"
  "@types/react-dom": "19.1.3"
  "@types/hast": "^3.0.4"
  "@types/nprogress": "^0.2.3"
  "@types/react-medium-image-zoom": "^3.0.3"
  
  # 其他工具
  "fast-glob": "^3.3.3"
  "nprogress": "^0.2.0"
  "unist-util-visit": "^5.0.0"
  "tsup": "^8.3.5"
