// @ts-nocheck -- skip type checking
import * as docs_9 from "../src/mdx/docs/framework/(showcase)/step.mdx?collection=docs&hash=1746459421211"
import * as docs_8 from "../src/mdx/docs/framework/(showcase)/index.mdx?collection=docs&hash=1746459421211"
import * as docs_7 from "../src/mdx/docs/framework/rest.mdx?collection=docs&hash=1746459421211"
import * as docs_6 from "../src/mdx/docs/framework/index.mdx?collection=docs&hash=1746459421211"
import * as docs_5 from "../src/mdx/docs/framework/fumadocs.mdx?collection=docs&hash=1746459421211"
import * as docs_4 from "../src/mdx/docs/framework/code-block.mdx?collection=docs&hash=1746459421211"
import * as docs_3 from "../src/mdx/docs/framework/clerk-setup.mdx?collection=docs&hash=1746459421211"
import * as docs_2 from "../src/mdx/docs/framework/clerk-quick-start.mdx?collection=docs&hash=1746459421211"
import * as docs_1 from "../src/mdx/docs/core/index.mdx?collection=docs&hash=1746459421211"
import * as docs_0 from "../src/mdx/docs/core/clerk-quick-start.mdx?collection=docs&hash=1746459421211"
import * as blog_3 from "../src/mdx/blog/why-docs.mdx?collection=blog&hash=1746459421211"
import * as blog_2 from "../src/mdx/blog/v15-2.mdx?collection=blog&hash=1746459421211"
import * as blog_1 from "../src/mdx/blog/make-a-blog.mdx?collection=blog&hash=1746459421211"
import * as blog_0 from "../src/mdx/blog/customize-ui.mdx?collection=blog&hash=1746459421211"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const blog = _runtime.doc<typeof _source.blog>([{ info: {"path":"customize-ui.mdx","absolutePath":"/Users/funeye/IdeaProjects/next-ai-build/src/mdx/blog/customize-ui.mdx"}, data: blog_0 }, { info: {"path":"make-a-blog.mdx","absolutePath":"/Users/funeye/IdeaProjects/next-ai-build/src/mdx/blog/make-a-blog.mdx"}, data: blog_1 }, { info: {"path":"v15-2.mdx","absolutePath":"/Users/funeye/IdeaProjects/next-ai-build/src/mdx/blog/v15-2.mdx"}, data: blog_2 }, { info: {"path":"why-docs.mdx","absolutePath":"/Users/funeye/IdeaProjects/next-ai-build/src/mdx/blog/why-docs.mdx"}, data: blog_3 }]);
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"core/clerk-quick-start.mdx","absolutePath":"/Users/funeye/IdeaProjects/next-ai-build/src/mdx/docs/core/clerk-quick-start.mdx"}, data: docs_0 }, { info: {"path":"core/index.mdx","absolutePath":"/Users/funeye/IdeaProjects/next-ai-build/src/mdx/docs/core/index.mdx"}, data: docs_1 }, { info: {"path":"framework/clerk-quick-start.mdx","absolutePath":"/Users/funeye/IdeaProjects/next-ai-build/src/mdx/docs/framework/clerk-quick-start.mdx"}, data: docs_2 }, { info: {"path":"framework/clerk-setup.mdx","absolutePath":"/Users/funeye/IdeaProjects/next-ai-build/src/mdx/docs/framework/clerk-setup.mdx"}, data: docs_3 }, { info: {"path":"framework/code-block.mdx","absolutePath":"/Users/funeye/IdeaProjects/next-ai-build/src/mdx/docs/framework/code-block.mdx"}, data: docs_4 }, { info: {"path":"framework/fumadocs.mdx","absolutePath":"/Users/funeye/IdeaProjects/next-ai-build/src/mdx/docs/framework/fumadocs.mdx"}, data: docs_5 }, { info: {"path":"framework/index.mdx","absolutePath":"/Users/funeye/IdeaProjects/next-ai-build/src/mdx/docs/framework/index.mdx"}, data: docs_6 }, { info: {"path":"framework/rest.mdx","absolutePath":"/Users/funeye/IdeaProjects/next-ai-build/src/mdx/docs/framework/rest.mdx"}, data: docs_7 }, { info: {"path":"framework/(showcase)/index.mdx","absolutePath":"/Users/funeye/IdeaProjects/next-ai-build/src/mdx/docs/framework/(showcase)/index.mdx"}, data: docs_8 }, { info: {"path":"framework/(showcase)/step.mdx","absolutePath":"/Users/funeye/IdeaProjects/next-ai-build/src/mdx/docs/framework/(showcase)/step.mdx"}, data: docs_9 }], [{"info":{"path":"core/meta.json","absolutePath":"/Users/funeye/IdeaProjects/next-ai-build/src/mdx/docs/core/meta.json"},"data":{"title":"Re8ger's Core","pages":["---Guide---","index","---Configuration---","clerk-quick-start","---Features---"],"description":"What is Re8ger's Core?","root":true,"icon":"Zap"}}, {"info":{"path":"framework/meta.json","absolutePath":"/Users/funeye/IdeaProjects/next-ai-build/src/mdx/docs/framework/meta.json"},"data":{"title":"Re8ger's Framework","pages":["---Guide---","index","fumadocs","clerk-quick-start","---Configuration---","clerk-setup","---Features---","code-block","(showcase)","---Rest---","..."],"description":"What is Re8ger's Framework?","root":true,"icon":"Pencil"}}, {"info":{"path":"framework/(showcase)/meta.json","absolutePath":"/Users/funeye/IdeaProjects/next-ai-build/src/mdx/docs/framework/(showcase)/meta.json"},"data":{"pages":["step","index"]}}])