SELECT
    u.id               AS user_pk,
    u.user_id,
    u.status,
    u.fingerprint_id,
    u.clerk_user_id,
    u.stripe_cus_id,
    u.email,
    u.created_at       AS user_created_at,
    u.updated_at       AS user_updated_at,
    c.id               AS credit_pk,
    c.balance_free,
    c.total_free_limit,
    c.free_start,
    c.free_end,
    c.balance_paid,
    c.total_paid_limit,
    c.paid_start,
    c.paid_end,
    c.balance_onetime_paid,
    c.total_onetime_paid_limit,
    c.onetime_paid_start,
    c.onetime_paid_end,
    c.created_at       AS credit_created_at,
    c.updated_at       AS credit_updated_at,
    s.id               AS subscription_pk,
    s.status           AS subscription_status,
    s.pay_subscription_id,
    s.price_id,
    s.price_name,
    s.credits_allocated,
    s.sub_period_start,
    s.sub_period_end,
    s.created_at       AS subscription_created_at,
    s.updated_at       AS subscription_updated_at,
    s.deleted          AS subscription_deleted
  FROM public.users u
  LEFT JOIN public.credits       c ON c.user_id = u.user_id
  LEFT JOIN public.subscriptions s ON s.user_id = u.user_id
  WHERE u.user_id = "6c19e13c-fa37-4c2a-9a5d-0401da043b09";